[package]
name = "pretix_request"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["rustls-tls", "json"], default-features = false}
serde = { version = "1.0.204", features = ["derive"] }